# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to ${{ matrix.environment }} via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 64.23.197.171
          username: zenApp
          password: zenApp
          local-dir: ./
          server-dir: c:/xampp/htdocs/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
